version: '3.8'

services:
  app:
    # Utilisation d'une image basée sur Debian (Bookworm) avec glibc et bash natifs
    image: node:24-bookworm

    container_name: nextjs_sandbox
    working_dir: /app
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      # Synchronisation du dossier racine
      - .:/app
      # Volume anonyme recommandé pour isoler les dépendances compilées du conteneur
      - /app/node_modules
    # Maintient le conteneur actif sans rien exécuter au démarrage
    command: tail -f /dev/null
    stdin_open: true
    tty: true