version: '3.8'

services:
  app:
    image: node:24-alpine

    container_name: nextjs_sandbox
    working_dir: /app
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      # Tout le dossier racine est synchronisé avec le conteneur
      - .:/app
    # Maintient le conteneur actif sans rien exécuter au démarrage
    command: tail -f /dev/null
    stdin_open: true
    tty: true