classDiagram
    class Client {
        +string nom
        +string prenom
        +string email
        +string telephone
        +reserverCreneau()
    }

    class Administrateur {
        +string identifiant
        +string motDePasse
        +string role
        +annulerReservation(refReservation: string)
    }

    class Reservation {
        +string reference
        +DateTime dateDepart
        +string heureDepart
        +StatutReservation statut
        +annuler()
        +calculerMontantTotal() float
    }

    class Billet {
        +CategoriePassager categorie
        +float prixUnitaire
    }

    class TypeDeSortie {
        +string nomPrestation
        +string lieuDepart
        +FormatSortie format
    }

    class Notification {
        +string message
        +DateTime dateEnvoi
        +TypeNotification type
        +envoyer()
    }

    class StatutReservation {
        <<enumeration>>
        CONFIRMEE
        ANNULEE
    }

    class CategoriePassager {
        <<enumeration>>
        ADULTE
        ENFANT_4_11
    }

    %% Relations
    Client "1" -- "0..*" Reservation : effectue
    Administrateur ..> Reservation : gère l'annulation
    Reservation "1" *-- "1..*" Billet : contient
    Reservation "1" --> "1" TypeDeSortie : concerne
    Reservation "1" --> "0..*" Notification : déclenche
    Billet --> CategoriePassager : type